# Generated by Terraform (lab: postgresql-single). Regenerate after every deploy, see the lab README.
# The PMM server is the jump host (ProxyJump): it only relays the connection, your key stays on your machine.

Host pmm-server
    HostName ${pmm_server_public_ip}
    User ec2-user
%{ if ssh_private_key_path != null ~}
    IdentityFile "${ssh_private_key_path}"
%{ endif ~}
    UserKnownHostsFile ~/.ssh/aws-postgresql-lab_known_hosts
    StrictHostKeyChecking accept-new

Host postgresql-source
    HostName ${postgresql_internal_ip}
    User ec2-user
%{ if ssh_private_key_path != null ~}
    IdentityFile "${ssh_private_key_path}"
%{ endif ~}
    UserKnownHostsFile ~/.ssh/aws-postgresql-lab_known_hosts
    StrictHostKeyChecking accept-new
    ProxyJump pmm-server
