---
- name: Restart PostgreSQL
  ansible.builtin.systemd_service:
    name: "{{ postgresql_service }}"
    state: restarted

- name: Reload PostgreSQL
  ansible.builtin.systemd_service:
    name: "{{ postgresql_service }}"
    state: reloaded
