---
# Admin tools installed on every lab server.
common_packages:
  - bash-completion
  - bat
  - bind-utils
  - btop
  - curl
  - git
  - "{{ 'iotop-c' if ansible_facts['distribution_major_version'] | int >= 10 else 'iotop' }}" # iotop became iotop-c in EL10
  - telnet
  - vim
